### PR TITLE
Feature/implement scan algorithm

### PR DESCRIPTION
**Pull request by philip-bbaale**

### CODE REVIEW

**Comment by victor-kironde** [comment]
@philip-bbaale From the branch name, there should be `1 - 2` files changed.
Why does the PR contain changes from 15 files? 
Screenshot 2021-10-13 at 14 57 31

**Comment by philip-bbaale** [comment]
@victor-kironde Noted. It will not happen again.

**Comment by victor-kironde** [comment]
@philip-bbaale This has happened so many times. Please update the PR to only have the relevant changes. 

Also fix these spelling mistakes.
Screenshot 2021-10-13 at 15 01 30

**Comment by philip-bbaale** [comment]
@victor-kironde All the changes are relevant to the branch. I will update the misspellings and inappropriate commit names.

**Comment by victor-kironde** [comment]
@philip-bbaale How is the full `ReadMe`, that already exists on the base branch, relevant to this branch?
Same for `elevator.py`, `operator.py` or their tests?

`feature/implement-scan-algorithm` should only have the scan algorithm, and its tests, nothing more.

Your PR has those files, and literally every other file in the project.

Why is this so hard for you to understand?

**Comment by victor-kironde** [comment]
Please address each review comment, and indicate with a reply that you've made the necessary changes.
Don't delete or overwrite the branch, or all review comments might get lost.

**Comment by philip-bbaale** [comment]
> Please address each review comment, and indicate with a reply that you've made the necessary changes. Don't delete or overwrite the branch, or all review comments might get lost.

I have renamed all commits with wrong naming and spelling mistakes.
That is commits, `b077922`, `bd0Be71` and `e3afad2`

**Comment by philip-bbaale** [comment]
> @philip-bbaale How is the full `ReadMe`, that already exists on the base branch, relevant to this branch? Same for `elevator.py`, `operator.py` or their tests?
> 
> `feature/implement-scan-algorithm` should only have the scan algorithm, and its tests, nothing more.
> 
> Your PR has those files, and literally every other file in the project.
> 
> Why is this so hard for you to understand?

The Implement-scan-algorithm branch was existent before you made an issue to add .readMe files to the branches. I, could not pull from the base branch as it had its own changes and therefore, added .readMe files to each relevant functioning branch.

For elevator.py, operator.py, and main.py I added docstrings and comments as I did in other branches as well. I also could not rebase or pull from the base branch as they all had different changes.

**Comment by victor-kironde** [comment]
> The Implement-scan-algorithm branch was existent before you made an issue to add .readMe files to the branches. I, could not pull from the base branch as it had its own changes and therefore, added .readMe files to each relevant functioning branch.
> 


I did not ask you to "add .readMe files to the branches". I asked to add **a ReadMe file**.

> I, could not pull from the base branch as it had its own changes and therefore, added .readMe files to each relevant functioning branch.

Git doesn't work like that at all. Theres a single file, and different branches can have different versions of that same file. Thats why it's called **Version Control**
What would be the point of branches if you have to update each of them separately?

I explicitly asked you to create a different branch, and PR for every issue.
So I would have expected a branch, `chore/add-readme` and a pull request, with only changes to the ReadMe file.
It seems like you didn't understand at all.
You didn't create such a PR and you didn't address all the points from that issue.
Same for docstrings issue, I expected a branch and PR to develop where the only changes in the files are additions of docstrings.

> For elevator.py, operator.py, and main.py I added docstrings and comments as I did in other branches as well. I also could not rebase or pull from the base branch as they all had different changes.


It's clear you still don't understand how git works.

**Comment by philip-bbaale** [comment]
> 
> 
> > The Implement-scan-algorithm branch was existent before you made an issue to add .readMe files to the branches. I, could not pull from the base branch as it had its own changes and therefore, added .readMe files to each relevant functioning branch.
> 
> > 
> 
> 
> 
> 
> 
> I did not ask you to "add .readMe files to the branches". I asked to add **a ReadMe file**.
> 
> 
> 
> > I, could not pull from the base branch as it had its own changes and therefore, added .readMe files to each relevant functioning branch.
> 
> 
> 
> Git doesn't work like that at all. Theres a single file, and different branches can have different versions of that same file. Thats why it's called **Version Control**
> 
> What would be the point of branches if you have to update each of them separately?
> 
> 
> 
> I explicitly asked you to create a different branch, and PR for every issue.
> 
> So I would have expected a branch, `chore/add-readme` and a pull request, with only changes to the ReadMe file.
> 
> It seems like you didn't understand at all.
> 
> You didn't create such a PR and you didn't address all the points from that issue.
> 
> Same for docstrings issue, I expected a branch and PR to develop where the only changes in the files are additions of docstrings.
> 
> 
> 
> > For elevator.py, operator.py, and main.py I added docstrings and comments as I did in other branches as well. I also could not rebase or pull from the base branch as they all had different changes.
> 
> 
> 
> 
> 
> It's clear you still don't understand how git works. 

@victor-kironde I made most of the changes to the development branch as you had listed them while making commits. I have learned to now make branches for every specific change or implementation.

**Comment by victor-kironde** [comment]
@philip-bbaale why have you not addressed any of the code review comments here?
Did you see them?

**Pull request closed without merging**
